# Auto-generated by AppForge — suppress R8 warnings for optional dependencies
-dontwarn com.google.mlkit.vision.text.chinese.**
-dontwarn com.google.mlkit.vision.text.devanagari.**
-dontwarn com.google.mlkit.vision.text.japanese.**
-dontwarn com.google.mlkit.vision.text.korean.**
-keep class io.flutter.** { *; }
-dontwarn io.flutter.embedding.**
